# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='products.proto',
  package='products',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eproducts.proto\x12\x08products\"\x81\x02\n\x12ProductItemMessage\x12\x11\n\tseller_id\x18\x01 \x01(\x05\x12\x13\n\x06prodid\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04name\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08\x63\x61tegory\x18\x04 \x01(\x05H\x02\x88\x01\x01\x12\x16\n\tcondition\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x12\n\x05price\x18\x06 \x01(\x02H\x04\x88\x01\x01\x12\x15\n\x08quantity\x18\x07 \x01(\x05H\x05\x88\x01\x01\x12\x10\n\x08keywords\x18\x08 \x03(\tB\t\n\x07_prodidB\x07\n\x05_nameB\x0b\n\t_categoryB\x0c\n\n_conditionB\x08\n\x06_priceB\x0b\n\t_quantity\"E\n\x13ProductsListMessage\x12.\n\x08products\x18\x01 \x03(\x0b\x32\x1c.products.ProductItemMessage\"\x1e\n\x0fgeneralResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x9a\x03\n\x08Products\x12M\n\x10\x41\x64\x64SellerProduct\x12\x1c.products.ProductItemMessage\x1a\x19.products.generalResponse\"\x00\x12N\n\x11\x45\x64itSellerProduct\x12\x1c.products.ProductItemMessage\x1a\x19.products.generalResponse\"\x00\x12N\n\x11GetSellerProducts\x12\x1c.products.ProductItemMessage\x1a\x19.products.generalResponse\"\x00\x12P\n\x13RemoveSellerProduct\x12\x1c.products.ProductItemMessage\x1a\x19.products.generalResponse\"\x00\x12M\n\x10GetSellerRatings\x12\x1c.products.ProductItemMessage\x1a\x19.products.generalResponse\"\x00\x62\x06proto3'
)




_PRODUCTITEMMESSAGE = _descriptor.Descriptor(
  name='ProductItemMessage',
  full_name='products.ProductItemMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seller_id', full_name='products.ProductItemMessage.seller_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prodid', full_name='products.ProductItemMessage.prodid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='products.ProductItemMessage.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='products.ProductItemMessage.category', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='condition', full_name='products.ProductItemMessage.condition', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='products.ProductItemMessage.price', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='products.ProductItemMessage.quantity', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keywords', full_name='products.ProductItemMessage.keywords', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_prodid', full_name='products.ProductItemMessage._prodid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='products.ProductItemMessage._name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_category', full_name='products.ProductItemMessage._category',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_condition', full_name='products.ProductItemMessage._condition',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_price', full_name='products.ProductItemMessage._price',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_quantity', full_name='products.ProductItemMessage._quantity',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=29,
  serialized_end=286,
)


_PRODUCTSLISTMESSAGE = _descriptor.Descriptor(
  name='ProductsListMessage',
  full_name='products.ProductsListMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='products', full_name='products.ProductsListMessage.products', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=357,
)


_GENERALRESPONSE = _descriptor.Descriptor(
  name='generalResponse',
  full_name='products.generalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='products.generalResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=389,
)

_PRODUCTITEMMESSAGE.oneofs_by_name['_prodid'].fields.append(
  _PRODUCTITEMMESSAGE.fields_by_name['prodid'])
_PRODUCTITEMMESSAGE.fields_by_name['prodid'].containing_oneof = _PRODUCTITEMMESSAGE.oneofs_by_name['_prodid']
_PRODUCTITEMMESSAGE.oneofs_by_name['_name'].fields.append(
  _PRODUCTITEMMESSAGE.fields_by_name['name'])
_PRODUCTITEMMESSAGE.fields_by_name['name'].containing_oneof = _PRODUCTITEMMESSAGE.oneofs_by_name['_name']
_PRODUCTITEMMESSAGE.oneofs_by_name['_category'].fields.append(
  _PRODUCTITEMMESSAGE.fields_by_name['category'])
_PRODUCTITEMMESSAGE.fields_by_name['category'].containing_oneof = _PRODUCTITEMMESSAGE.oneofs_by_name['_category']
_PRODUCTITEMMESSAGE.oneofs_by_name['_condition'].fields.append(
  _PRODUCTITEMMESSAGE.fields_by_name['condition'])
_PRODUCTITEMMESSAGE.fields_by_name['condition'].containing_oneof = _PRODUCTITEMMESSAGE.oneofs_by_name['_condition']
_PRODUCTITEMMESSAGE.oneofs_by_name['_price'].fields.append(
  _PRODUCTITEMMESSAGE.fields_by_name['price'])
_PRODUCTITEMMESSAGE.fields_by_name['price'].containing_oneof = _PRODUCTITEMMESSAGE.oneofs_by_name['_price']
_PRODUCTITEMMESSAGE.oneofs_by_name['_quantity'].fields.append(
  _PRODUCTITEMMESSAGE.fields_by_name['quantity'])
_PRODUCTITEMMESSAGE.fields_by_name['quantity'].containing_oneof = _PRODUCTITEMMESSAGE.oneofs_by_name['_quantity']
_PRODUCTSLISTMESSAGE.fields_by_name['products'].message_type = _PRODUCTITEMMESSAGE
DESCRIPTOR.message_types_by_name['ProductItemMessage'] = _PRODUCTITEMMESSAGE
DESCRIPTOR.message_types_by_name['ProductsListMessage'] = _PRODUCTSLISTMESSAGE
DESCRIPTOR.message_types_by_name['generalResponse'] = _GENERALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProductItemMessage = _reflection.GeneratedProtocolMessageType('ProductItemMessage', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTITEMMESSAGE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.ProductItemMessage)
  })
_sym_db.RegisterMessage(ProductItemMessage)

ProductsListMessage = _reflection.GeneratedProtocolMessageType('ProductsListMessage', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTSLISTMESSAGE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.ProductsListMessage)
  })
_sym_db.RegisterMessage(ProductsListMessage)

generalResponse = _reflection.GeneratedProtocolMessageType('generalResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERALRESPONSE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:products.generalResponse)
  })
_sym_db.RegisterMessage(generalResponse)



_PRODUCTS = _descriptor.ServiceDescriptor(
  name='Products',
  full_name='products.Products',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=392,
  serialized_end=802,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddSellerProduct',
    full_name='products.Products.AddSellerProduct',
    index=0,
    containing_service=None,
    input_type=_PRODUCTITEMMESSAGE,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EditSellerProduct',
    full_name='products.Products.EditSellerProduct',
    index=1,
    containing_service=None,
    input_type=_PRODUCTITEMMESSAGE,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSellerProducts',
    full_name='products.Products.GetSellerProducts',
    index=2,
    containing_service=None,
    input_type=_PRODUCTITEMMESSAGE,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveSellerProduct',
    full_name='products.Products.RemoveSellerProduct',
    index=3,
    containing_service=None,
    input_type=_PRODUCTITEMMESSAGE,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSellerRatings',
    full_name='products.Products.GetSellerRatings',
    index=4,
    containing_service=None,
    input_type=_PRODUCTITEMMESSAGE,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODUCTS)

DESCRIPTOR.services_by_name['Products'] = _PRODUCTS

# @@protoc_insertion_point(module_scope)
