# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import customers_pb2 as customers__pb2


class CustomersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRowsByColumn = channel.unary_unary(
                '/customers.Customers/GetRowsByColumn',
                request_serializer=customers__pb2.SelectOneMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.GetRowByMultiColumns = channel.unary_unary(
                '/customers.Customers/GetRowByMultiColumns',
                request_serializer=customers__pb2.SelectManyMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.InsertSeller = channel.unary_unary(
                '/customers.Customers/InsertSeller',
                request_serializer=customers__pb2.InsertMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.UpdateRowByColumn = channel.unary_unary(
                '/customers.Customers/UpdateRowByColumn',
                request_serializer=customers__pb2.UpdateMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.CreateAccount = channel.unary_unary(
                '/customers.Customers/CreateAccount',
                request_serializer=customers__pb2.CreateAccountMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/customers.Customers/Login',
                request_serializer=customers__pb2.LoginMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.SearchProduct = channel.unary_unary(
                '/customers.Customers/SearchProduct',
                request_serializer=customers__pb2.SearchProductMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.AddToCart = channel.unary_unary(
                '/customers.Customers/AddToCart',
                request_serializer=customers__pb2.AddToCartMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.RemoveFromCart = channel.unary_unary(
                '/customers.Customers/RemoveFromCart',
                request_serializer=customers__pb2.RemoveFromCartMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.ClearCart = channel.unary_unary(
                '/customers.Customers/ClearCart',
                request_serializer=customers__pb2.ClearCartMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.DisplayCart = channel.unary_unary(
                '/customers.Customers/DisplayCart',
                request_serializer=customers__pb2.DisplayCartMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.MakePurchase = channel.unary_unary(
                '/customers.Customers/MakePurchase',
                request_serializer=customers__pb2.MakePurchaseMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.PurchaseHistory = channel.unary_unary(
                '/customers.Customers/PurchaseHistory',
                request_serializer=customers__pb2.PurchaseHistoryMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.ProvideFeedback = channel.unary_unary(
                '/customers.Customers/ProvideFeedback',
                request_serializer=customers__pb2.ProvideFeedbackMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.GetSellerRating = channel.unary_unary(
                '/customers.Customers/GetSellerRating',
                request_serializer=customers__pb2.GetSellerRatingMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/customers.Customers/Logout',
                request_serializer=customers__pb2.LogoutMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )


class CustomersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRowsByColumn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRowByMultiColumns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRowByColumn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurchaseHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRowsByColumn': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRowsByColumn,
                    request_deserializer=customers__pb2.SelectOneMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'GetRowByMultiColumns': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRowByMultiColumns,
                    request_deserializer=customers__pb2.SelectManyMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'InsertSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertSeller,
                    request_deserializer=customers__pb2.InsertMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'UpdateRowByColumn': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRowByColumn,
                    request_deserializer=customers__pb2.UpdateMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=customers__pb2.CreateAccountMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=customers__pb2.LoginMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'SearchProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProduct,
                    request_deserializer=customers__pb2.SearchProductMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=customers__pb2.AddToCartMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=customers__pb2.RemoveFromCartMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=customers__pb2.ClearCartMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'DisplayCart': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayCart,
                    request_deserializer=customers__pb2.DisplayCartMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'MakePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePurchase,
                    request_deserializer=customers__pb2.MakePurchaseMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'PurchaseHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseHistory,
                    request_deserializer=customers__pb2.PurchaseHistoryMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'ProvideFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideFeedback,
                    request_deserializer=customers__pb2.ProvideFeedbackMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=customers__pb2.GetSellerRatingMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=customers__pb2.LogoutMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customers.Customers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Customers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRowsByColumn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/GetRowsByColumn',
            customers__pb2.SelectOneMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRowByMultiColumns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/GetRowByMultiColumns',
            customers__pb2.SelectManyMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/InsertSeller',
            customers__pb2.InsertMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRowByColumn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/UpdateRowByColumn',
            customers__pb2.UpdateMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/CreateAccount',
            customers__pb2.CreateAccountMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/Login',
            customers__pb2.LoginMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/SearchProduct',
            customers__pb2.SearchProductMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/AddToCart',
            customers__pb2.AddToCartMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/RemoveFromCart',
            customers__pb2.RemoveFromCartMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/ClearCart',
            customers__pb2.ClearCartMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisplayCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/DisplayCart',
            customers__pb2.DisplayCartMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MakePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/MakePurchase',
            customers__pb2.MakePurchaseMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurchaseHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/PurchaseHistory',
            customers__pb2.PurchaseHistoryMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProvideFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/ProvideFeedback',
            customers__pb2.ProvideFeedbackMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/GetSellerRating',
            customers__pb2.GetSellerRatingMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/Logout',
            customers__pb2.LogoutMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
