# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import products_pb2 as products__pb2


class ProductsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRowsByColumn = channel.unary_unary(
                '/products.Products/GetRowsByColumn',
                request_serializer=products__pb2.SelectOneMessage.SerializeToString,
                response_deserializer=products__pb2.generalResponse.FromString,
                )
        self.GetRowByMultiColumns = channel.unary_unary(
                '/products.Products/GetRowByMultiColumns',
                request_serializer=products__pb2.SelectManyMessage.SerializeToString,
                response_deserializer=products__pb2.generalResponse.FromString,
                )
        self.InsertProduct = channel.unary_unary(
                '/products.Products/InsertProduct',
                request_serializer=products__pb2.InsertMessage.SerializeToString,
                response_deserializer=products__pb2.generalResponse.FromString,
                )
        self.UpdateRowByColumn = channel.unary_unary(
                '/products.Products/UpdateRowByColumn',
                request_serializer=products__pb2.UpdateMessage.SerializeToString,
                response_deserializer=products__pb2.generalResponse.FromString,
                )
        self.UpdateRowByMulti = channel.unary_unary(
                '/products.Products/UpdateRowByMulti',
                request_serializer=products__pb2.UpdateManyMessage.SerializeToString,
                response_deserializer=products__pb2.generalResponse.FromString,
                )
        self.DeleteRow = channel.unary_unary(
                '/products.Products/DeleteRow',
                request_serializer=products__pb2.DeleteMessage.SerializeToString,
                response_deserializer=products__pb2.generalResponse.FromString,
                )
        self.SearchProduct = channel.unary_unary(
                '/products.Products/SearchProduct',
                request_serializer=products__pb2.SearchProductsRequestMessage.SerializeToString,
                response_deserializer=products__pb2.SearchProductsResponseMessage.FromString,
                )


class ProductsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRowsByColumn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRowByMultiColumns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRowByColumn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRowByMulti(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRowsByColumn': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRowsByColumn,
                    request_deserializer=products__pb2.SelectOneMessage.FromString,
                    response_serializer=products__pb2.generalResponse.SerializeToString,
            ),
            'GetRowByMultiColumns': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRowByMultiColumns,
                    request_deserializer=products__pb2.SelectManyMessage.FromString,
                    response_serializer=products__pb2.generalResponse.SerializeToString,
            ),
            'InsertProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertProduct,
                    request_deserializer=products__pb2.InsertMessage.FromString,
                    response_serializer=products__pb2.generalResponse.SerializeToString,
            ),
            'UpdateRowByColumn': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRowByColumn,
                    request_deserializer=products__pb2.UpdateMessage.FromString,
                    response_serializer=products__pb2.generalResponse.SerializeToString,
            ),
            'UpdateRowByMulti': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRowByMulti,
                    request_deserializer=products__pb2.UpdateManyMessage.FromString,
                    response_serializer=products__pb2.generalResponse.SerializeToString,
            ),
            'DeleteRow': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRow,
                    request_deserializer=products__pb2.DeleteMessage.FromString,
                    response_serializer=products__pb2.generalResponse.SerializeToString,
            ),
            'SearchProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProduct,
                    request_deserializer=products__pb2.SearchProductsRequestMessage.FromString,
                    response_serializer=products__pb2.SearchProductsResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'products.Products', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Products(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRowsByColumn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/products.Products/GetRowsByColumn',
            products__pb2.SelectOneMessage.SerializeToString,
            products__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRowByMultiColumns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/products.Products/GetRowByMultiColumns',
            products__pb2.SelectManyMessage.SerializeToString,
            products__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/products.Products/InsertProduct',
            products__pb2.InsertMessage.SerializeToString,
            products__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRowByColumn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/products.Products/UpdateRowByColumn',
            products__pb2.UpdateMessage.SerializeToString,
            products__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRowByMulti(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/products.Products/UpdateRowByMulti',
            products__pb2.UpdateManyMessage.SerializeToString,
            products__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/products.Products/DeleteRow',
            products__pb2.DeleteMessage.SerializeToString,
            products__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/products.Products/SearchProduct',
            products__pb2.SearchProductsRequestMessage.SerializeToString,
            products__pb2.SearchProductsResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
