# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import customers_pb2 as customers__pb2


class CustomersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRowsByColumn = channel.unary_unary(
                '/customers.Customers/GetRowsByColumn',
                request_serializer=customers__pb2.SelectOneMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.GetRowByMultiColumns = channel.unary_unary(
                '/customers.Customers/GetRowByMultiColumns',
                request_serializer=customers__pb2.SelectManyMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.InsertSeller = channel.unary_unary(
                '/customers.Customers/InsertSeller',
                request_serializer=customers__pb2.InsertMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )
        self.UpdateRowByColumn = channel.unary_unary(
                '/customers.Customers/UpdateRowByColumn',
                request_serializer=customers__pb2.UpdateMessage.SerializeToString,
                response_deserializer=customers__pb2.generalResponse.FromString,
                )


class CustomersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRowsByColumn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRowByMultiColumns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRowByColumn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRowsByColumn': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRowsByColumn,
                    request_deserializer=customers__pb2.SelectOneMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'GetRowByMultiColumns': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRowByMultiColumns,
                    request_deserializer=customers__pb2.SelectManyMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'InsertSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertSeller,
                    request_deserializer=customers__pb2.InsertMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
            'UpdateRowByColumn': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRowByColumn,
                    request_deserializer=customers__pb2.UpdateMessage.FromString,
                    response_serializer=customers__pb2.generalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customers.Customers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Customers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRowsByColumn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/GetRowsByColumn',
            customers__pb2.SelectOneMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRowByMultiColumns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/GetRowByMultiColumns',
            customers__pb2.SelectManyMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/InsertSeller',
            customers__pb2.InsertMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRowByColumn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/customers.Customers/UpdateRowByColumn',
            customers__pb2.UpdateMessage.SerializeToString,
            customers__pb2.generalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
