# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='customers.proto',
  package='customers',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63ustomers.proto\x12\tcustomers\"D\n\rInsertMessage\x12\x12\n\ntable_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x01(\t\"r\n\rUpdateMessage\x12\x12\n\ntable_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x01(\t\x12\x15\n\rcondition_col\x18\x04 \x01(\t\x12\x15\n\rcondition_val\x18\x05 \x01(\x05\"L\n\x10SelectOneMessage\x12\x12\n\ntable_name\x18\x01 \x01(\t\x12\x0e\n\x06\x63olumn\x18\x02 \x01(\t\x12\x14\n\x0csearch_value\x18\x03 \x01(\t\"i\n\x11SelectManyMessage\x12\x12\n\ntable_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\t\x12\x15\n\rsearch_values\x18\x03 \x01(\t\x12\x18\n\x10selected_columns\x18\x04 \x01(\t\"\x1e\n\x0fgeneralResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xc2\x02\n\tCustomers\x12L\n\x0fGetRowsByColumn\x12\x1b.customers.SelectOneMessage\x1a\x1a.customers.generalResponse\"\x00\x12R\n\x14GetRowByMultiColumns\x12\x1c.customers.SelectManyMessage\x1a\x1a.customers.generalResponse\"\x00\x12\x46\n\x0cInsertSeller\x12\x18.customers.InsertMessage\x1a\x1a.customers.generalResponse\"\x00\x12K\n\x11UpdateRowByColumn\x12\x18.customers.UpdateMessage\x1a\x1a.customers.generalResponse\"\x00\x62\x06proto3'
)




_INSERTMESSAGE = _descriptor.Descriptor(
  name='InsertMessage',
  full_name='customers.InsertMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_name', full_name='customers.InsertMessage.table_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columns', full_name='customers.InsertMessage.columns', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='customers.InsertMessage.values', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=98,
)


_UPDATEMESSAGE = _descriptor.Descriptor(
  name='UpdateMessage',
  full_name='customers.UpdateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_name', full_name='customers.UpdateMessage.table_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columns', full_name='customers.UpdateMessage.columns', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='customers.UpdateMessage.values', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='condition_col', full_name='customers.UpdateMessage.condition_col', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='condition_val', full_name='customers.UpdateMessage.condition_val', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=214,
)


_SELECTONEMESSAGE = _descriptor.Descriptor(
  name='SelectOneMessage',
  full_name='customers.SelectOneMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_name', full_name='customers.SelectOneMessage.table_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column', full_name='customers.SelectOneMessage.column', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search_value', full_name='customers.SelectOneMessage.search_value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=292,
)


_SELECTMANYMESSAGE = _descriptor.Descriptor(
  name='SelectManyMessage',
  full_name='customers.SelectManyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_name', full_name='customers.SelectManyMessage.table_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columns', full_name='customers.SelectManyMessage.columns', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='search_values', full_name='customers.SelectManyMessage.search_values', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='selected_columns', full_name='customers.SelectManyMessage.selected_columns', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=399,
)


_GENERALRESPONSE = _descriptor.Descriptor(
  name='generalResponse',
  full_name='customers.generalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='customers.generalResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=431,
)

DESCRIPTOR.message_types_by_name['InsertMessage'] = _INSERTMESSAGE
DESCRIPTOR.message_types_by_name['UpdateMessage'] = _UPDATEMESSAGE
DESCRIPTOR.message_types_by_name['SelectOneMessage'] = _SELECTONEMESSAGE
DESCRIPTOR.message_types_by_name['SelectManyMessage'] = _SELECTMANYMESSAGE
DESCRIPTOR.message_types_by_name['generalResponse'] = _GENERALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InsertMessage = _reflection.GeneratedProtocolMessageType('InsertMessage', (_message.Message,), {
  'DESCRIPTOR' : _INSERTMESSAGE,
  '__module__' : 'customers_pb2'
  # @@protoc_insertion_point(class_scope:customers.InsertMessage)
  })
_sym_db.RegisterMessage(InsertMessage)

UpdateMessage = _reflection.GeneratedProtocolMessageType('UpdateMessage', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMESSAGE,
  '__module__' : 'customers_pb2'
  # @@protoc_insertion_point(class_scope:customers.UpdateMessage)
  })
_sym_db.RegisterMessage(UpdateMessage)

SelectOneMessage = _reflection.GeneratedProtocolMessageType('SelectOneMessage', (_message.Message,), {
  'DESCRIPTOR' : _SELECTONEMESSAGE,
  '__module__' : 'customers_pb2'
  # @@protoc_insertion_point(class_scope:customers.SelectOneMessage)
  })
_sym_db.RegisterMessage(SelectOneMessage)

SelectManyMessage = _reflection.GeneratedProtocolMessageType('SelectManyMessage', (_message.Message,), {
  'DESCRIPTOR' : _SELECTMANYMESSAGE,
  '__module__' : 'customers_pb2'
  # @@protoc_insertion_point(class_scope:customers.SelectManyMessage)
  })
_sym_db.RegisterMessage(SelectManyMessage)

generalResponse = _reflection.GeneratedProtocolMessageType('generalResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERALRESPONSE,
  '__module__' : 'customers_pb2'
  # @@protoc_insertion_point(class_scope:customers.generalResponse)
  })
_sym_db.RegisterMessage(generalResponse)



_CUSTOMERS = _descriptor.ServiceDescriptor(
  name='Customers',
  full_name='customers.Customers',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=434,
  serialized_end=756,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRowsByColumn',
    full_name='customers.Customers.GetRowsByColumn',
    index=0,
    containing_service=None,
    input_type=_SELECTONEMESSAGE,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetRowByMultiColumns',
    full_name='customers.Customers.GetRowByMultiColumns',
    index=1,
    containing_service=None,
    input_type=_SELECTMANYMESSAGE,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InsertSeller',
    full_name='customers.Customers.InsertSeller',
    index=2,
    containing_service=None,
    input_type=_INSERTMESSAGE,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateRowByColumn',
    full_name='customers.Customers.UpdateRowByColumn',
    index=3,
    containing_service=None,
    input_type=_UPDATEMESSAGE,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMERS)

DESCRIPTOR.services_by_name['Customers'] = _CUSTOMERS

# @@protoc_insertion_point(module_scope)
